<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>openEulerReviewMonitor</AssemblyName>
    <Version>1.6.10</Version>
    <ApplicationIcon>Assets/openeuler.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>embedded</DebugType>
      <Authors>yanzhicong</Authors>
    <Copyright>© 2026 yanzhicong</Copyright>
  </PropertyGroup>
  <ItemGroup><Compile Remove="Tests/**/*.cs" /></ItemGroup>
  <ItemGroup><Resource Include="Assets/*.png"/><Resource Include="Assets/*.ico"/></ItemGroup>
</Project>

